In [128]:
import numpy as np

In [129]:
a = np.array([0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,5, 5, 5])
a_sorted = np.sort(a)

In [130]:
# prep 
u, c = np.unique(a_sorted, return_counts=True)
lranks = np.cumsum(c) - c + 1
hranks = np.cumsum(c)
u, c, lranks, hranks

(array([0, 1, 2, 3, 4, 5]),
 array([2, 1, 3, 5, 2, 3]),
 array([ 1,  3,  4,  7, 12, 14]),
 array([ 2,  3,  6, 11, 13, 16]))

In [131]:
x = np.array([0 , 1, 2, 2, 2.5, 3, 3, 3, 4.5, 5, 11])
indices = np.searchsorted(a_sorted, x)
indices

array([ 0,  2,  3,  3,  6,  6,  6,  6, 13, 13, 16])

In [132]:
in_train = np.isin(x, u)
in_train

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True, False])

In [133]:
u_indices = np.searchsorted(u, x[in_train])
x[in_train], u_indices

(array([0., 1., 2., 2., 3., 3., 3., 5.]), array([0, 1, 2, 2, 3, 3, 3, 5]))

In [134]:
lr, hr = lranks[u_indices], hranks[u_indices]
lr, hr

(array([ 1,  3,  4,  4,  7,  7,  7, 14]),
 array([ 2,  3,  6,  6, 11, 11, 11, 16]))

In [162]:
np.random.randint(0, hr - lr + 1) + lr

array([ 2,  3,  5,  4,  8, 10,  7, 16])

In [207]:
np.random.randint(lr, hr + 1) 

array([ 1,  3,  6,  4,  7,  7,  7, 15])

In [24]:
lranks

array([ 1,  3,  4,  7, 12, 14])